spring:
 datasource:
   url: jdbc:mysql://localhost:3306/lawwa
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver

 jpa:
   show-sql: true
   hibernate:
     ddl-auto: update

server:
  port: 8761 


# spring:
#   datasource:
#     driverClassName: org.postgresql.Driver
#     initialSize: 5
#     maxActive: 10
#     maxIdle: 5
#     minIdle: 2
#     removeAbandoned: true
#   jpa:
#     hibernate:
#       ddl:
#         auto: update
#     properties:
#       hibernate:
#         jdbc:
#           lob:
#             non_contextual_creation: true
#     show-sql: true
# server:
#   port: 8761
